[web]
type = "HttpListenInput"
address = "0.0.0.0:4881"

[debug_output]
type = "LogOutput"
message_matcher = "TRUE"
encoder = "PayloadEncoder"

[PayloadEncoder]
append_newlines = false
prefix_ts = true
ts_format = "2006/01/02 3:04:05PM MST"
